name: book_appointment
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#flutter pub run flutter_launcher_icons:main
#flutter pub run flutter_native_splash:create
#flutter pub run flutter_app_name
# flutter pub run flutter_launcher_icons:main
# flutter pub run change_app_package_name:main bmsc.ws.gis.store

version: 9.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  geocoder: ^0.2.1
  scoped_model: ^1.1.0
  geolocator: ^7.7.1
  paging: ^0.1.0
  loadmore: ^2.0.1
  flutter_pagination_helper: ^1.0.1+2
  permission_handler: ^8.2.6
  #  cupertino_icons: ^0.1.2
  google_fonts:
  http: ^0.13.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.2.1


  convert: ^3.0.1
  #  geolocator: ^7.7.1
  toast: ^0.1.5
  #  shared_preferences: ^2.0.8
  shared_preferences: ^2.0.8

  firebase_messaging: ^11.1.0
  email_validator: ^2.0.1

  google_maps_flutter: ^2.1.0
  url_launcher: ^6.0.12

  #  geocoder: ^0.2.1
  masked_text_input_formatter: ^0.0.1
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4+4
  firebase_analytics: ^8.3.4
  #  flutter_local_notifications: ^9.0.2
  #  device_info:
  #  flutter_native_admob:
  #  flutter_facebook_login:
  flutter_html:
  #facebook_audience_network:
  #facebook_audience_network:
  dio: ^4.0.1
  #  google_sign_in: ^5.2.1
  firebase_core: ^1.10.0

dependency_overrides:
  intl: ^0.17.0

  image_picker_platform_interface: ^2.4.1
  plugin_platform_interface: ^2.0.2
  process: ^3.0.9
  platform: ^3.0.2
  file: ^5.0.7
  archive: ^3.1.6
  yaml: ^3.1.0
  args: ^2.3.0
  test_api: ^0.4.6

  matcher: ^0.12.11
#  http: 0.12.2



dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^1.3.1
  flutter_launcher_name: "^0.0.1"



  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter
  test: ^1.19.2
  flutter_lints: ^1.0.0
  screenshots: ^2.1.1
flutter_app_name:
  name: "Patient App"
flutter_launcher_name:
  name: "Patient App"

flutter_native_splash:
  background_image: "assets/splash.png"


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/homeScreenImages/
    - assets/moreScreenImages/
    - assets/loginScreenImages/
    - assets/detailScreenImages/
    - assets/specialityScreenImages/
    - assets/makeAppointmentScreenImages/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family:
    #Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
