// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFftY8VPnBCAVIPVImvwNm6Isf6iGObho',
    appId: '1:398546324578:android:8285352b96bdbed169553b',
    messagingSenderId: '398546324578',
    projectId: 'doctor-b0cd1',
    storageBucket: 'doctor-b0cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSt1JuAyj94ursCVrdHpMm1wyt2qXUehM',
    appId: '1:398546324578:ios:0eba12a877ede15569553b',
    messagingSenderId: '398546324578',
    projectId: 'doctor-b0cd1',
    storageBucket: 'doctor-b0cd1.appspot.com',
    iosClientId: '398546324578-2fbt81hqohn6h3seov34fiidb6qfjc16.apps.googleusercontent.com',
    iosBundleId: 'zedan.bmsc.ws',
  );
}
